### ISSUE TITLE
Insert comments from HAR page entries into the JS when converting from HAR

### ISSUE THREAD

**Issue by robingustafsson** [grafana/har-to-k6#126]
If there's a comment attached to a page entry [1] include it as a comment in the generated JS script.

[1] - http://www.softwareishard.com/blog/har-12-spec/#pages

**Comment by codebien** [comment]
Moved here from the k6 repository, @e-fisher (as the last contributor) do you know if it is still a missing feature and if it is still relevant? If it has been implemented or it isn't relevant anymore then we should close it.

**Comment by e-fisher** [comment]
@codebien Tested and it's already implemented, thanks for bringing this to attention!
