### ISSUE TITLE
Missing post data MIME type (0) Error when converting fiddle archive

### ISSUE THREAD

**Issue by suntong** [grafana/har-to-k6#87]
```sh
$ har-to-k6 wikipedia.har -o wikipedia.js
Converting 'wikipedia.har'
Error converting archive:
Missing post data MIME type (0)
```

The `wikipedia.har` is from fiddle recording and attached.
[wikipedia.zip](https://github.com/grafana/har-to-k6/files/7289387/wikipedia.zip)

**Comment by KeiNguyen0809** [comment]
try this filter `"mimeType": ""` to find the error line then input appropriate value inside. For example: `"mimeType": "application/json"`
